using DynamoSharp.DynamoDb;
using DynamoSharp.DynamoDb.Configs;
using SimplePrimaryKey.Models;

namespace SimplePrimaryKey.Context;

public class UserContext : DynamoSharpContext
{
    public IDynamoDbSet<User> Users { get; } = null!;

    public UserContext(IDynamoDbContextAdapter dynamoDbContextAdapter, TableSchema tableSchema) : base(dynamoDbContextAdapter, tableSchema) { }

    // Partition Key and Sort Key are not defined, so they will be automatically generated by the library.
    // Example Partition Key: USER#D1ADDCA5-2B7B-4DE5-A221-C626C0A677F9
    // Example Sort Key: USER#D1ADDCA5-2B7B-4DE5-A221-C626C0A677F9
}
