using DynamoSharp.DynamoDb;
using DynamoSharp.DynamoDb.Configs;
using DynamoSharp.DynamoDb.ModelsBuilder;
using OneToMany.Models;

namespace OneToMany.Context;

public class EcommerceContext : DynamoSharpContext
{
    public IDynamoDbSet<Order> Orders { get; private set; } = null!;

    public EcommerceContext(IDynamoDbContextAdapter dynamoDbContextAdapter, TableSchema tableSchema) : base(dynamoDbContextAdapter, tableSchema)
    {
    }

    public override void OnModelCreating(IModelBuilder modelBuilder)
    {
        // Partition Key and Sort Key are not defined, so they will be automatically generated by the library.
        // Example Partition Key Order: ORDER#D1ADDCA5-2B7B-4DE5-A221-C626C0A677F9
        // Example Sort Key for Order: ORDER#D1ADDCA5-2B7B-4DE5-A221-C626C0A677F9

        // Example Partition Key Item: ORDER#D1ADDCA5-2B7B-4DE5-A221-C626C0A677F9
        // Example Sort Key for Item: ITEM#404E1BA3-6998-4FC2-8E57-C714C5B9BF81

        modelBuilder.Entity<Order>()
            .HasOneToMany(o => o.Items);
    }
}
